# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
