# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_stripe_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_token',
            new_name='card_token',
        ),
        migrations.AddField(
            model_name='user',
            name='customer_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
