# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
